[package]
name = "gitop"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.3", features = ["derive"] }
git2 = "0.18.0"
pretty_env_logger = "0.5.0"
log = "0.4.20"
clap-verbosity-flag = "2.0.1"
downcast-rs = "1.2.0"